{% set version = "1.15.0" %}

package:
  name: setuptools_scm
  version: {{ version }}

source:
  fn: setuptools_scm-{{ version }}.tar.gz
  url: https://github.com/pypa/setuptools_scm/archive/{{ version }}.tar.gz
  sha256: 9865a6b40e11dc3f4e4020110cd42b9e9cab04be9fc855984fcb4bbdbc8c5d1e

build:
  number: 0
  script: python -m pip install --no-deps .

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - setuptools_scm

about:
  home: https://github.com/pypa/setuptools_scm/
  license: MIT
  summary: 'The blessed package to manage your versions by scm tags.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
