{% set version = "3.0.2" %}

package:
  name: setuptools_scm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools_scm/setuptools_scm-{{ version }}.tar.gz
  sha256: 113cea38b2edba8538b7e608b58cbd7e09bb71b16d968a9b97e36b4805e06d59

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - setuptools_scm

about:
  home: https://github.com/pypa/setuptools_scm/
  license: MIT
  # license_file: LICENSE
  summary: 'The blessed package to manage your versions by scm tags.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - astaric
