{% set name = "setuptools_scm" %}
{% set version = "7.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c27bc1f48593cfc9527251f1f0fc41ce282ea57bbc7fd5a1ea3acb99325fab4c

build:
  number: 0

outputs:
  - name: setuptools-scm
    script: {{ PYTHON }} -m pip install . --no-deps -vv
    build:
      skip: True  # [py<37]
    requirements:
      host:
        - python
        - pip
        - setuptools
        - typing-extensions
      run:
        - python
        - importlib-metadata  # [py<38]
        - packaging >=20.0
        - setuptools >=45
        - tomli >=1.0.0
        - typing-extensions
    test:
      imports:
        - setuptools_scm
      requires:
        - pip
      commands:
        - pip check

  - name: setuptools_scm
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('setuptools-scm', max_pin="x.x.x") }}
    test:
      imports:
        - setuptools_scm

about:
  home: https://github.com/pypa/setuptools_scm/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The blessed package to manage your versions by scm tags
  dev_url: https://github.com/pypa/setuptools_scm/
  doc_url: https://github.com/pypa/setuptools_scm/blob/main/README.rst

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - astaric
