{% set name = "setuptools_scm" %}
{% set version = "9.2.2" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c674ab4665686a0887d7e24c03ab25f24201c213e82ea689d2f3e169ef7ef57

build:
  number: 0
  skip: true  # [py<38]

outputs:
  - name: setuptools-scm
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - pip
        - python
        - setuptools >=61
        - wheel
        - tomli <=2.0.2  # [py<311]
      run:
        - python
        - packaging >=20.0
        - setuptools
        - tomli >=1.0.0  # [py<311]
        - typing-extensions  # [py<310]
    # Upstream tests have a problem - importlib.metadata.PackageNotFoundError: No package metadata was found for build
    test:
      imports:
        - setuptools_scm
      requires:
        - pip
      commands:
        - pip check
        
  - name: setuptools_scm
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('setuptools-scm', max_pin="x.x.x") }}
    test:
      imports:
        - setuptools_scm

about:
  home: https://github.com/pypa/setuptools_scm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The blessed package to manage your versions by scm tags
  description: |
    setuptools_scm extracts Python package versions from git or hg metadata
    instead of declaring them as the version argument or in a SCM managed file.
  dev_url: https://github.com/pypa/setuptools_scm
  doc_url: https://github.com/pypa/setuptools_scm

extra:
  skip-lints:
    # Ignore linting errors on dummy setuptools_scm package
    - missing_python_build_tool
    - missing_wheel
    - missing_python
    - missing_pip_check
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - astaric
