travis:
  secure:
    BINSTAR_TOKEN: PxPN30MO3QinvAcLdOvCjGnvSi+KHf0lLR3KumZLX4kqmIUKEvWaki/CTQVzOFxmA8Q2/Gu644iU22erNGRqaqX1L2ax1ehFnS9Gm3ZO0UV6VBBdqna1VPuQz0qZvh9SYPTNd6NdOW9znMOHx0evTLFTfNIE2rdgxIXME9iCiAfIiNt10ik0MYR2fx1upcq302AwuFM2ZOKtTo+81xtI0wh9VJNYZZN+wHTRQW/yPzjv1b0t4FS73nBsYRiSu1hJZxQxU9HVViTtZFww3Ff7Ql9UzDM6bwuCsg7l8cZt8jHoocD6FunYYJKoqPQKU0DZTfvcNDbujeI57ieE6fMb6lg4R38nbZy+LvjRB15ZHWC750G5prCyIardrgmaQ4feTucWCIp4xwjoC8FaxTgQfKN+h6az/dz380n2WjZvMzuseugcShnNcXmCxgBSg17IbZAjArS3FcbrQt2W5IHWPy0jkjtcqazj/1R9A34a6C/19/7g7IO+biu/uFyvEjSBi+hJHf5XWSlVXmBuB5VnvKT69VLjYx1WWzGN/5u6ucqOHfsRkJjT1XdzfXnfyFV7e61dAwRyof4hwgfDVjvbjMSnHgRSVsnCJ8Zk+ACv4Gdkng56rJbxrj5q557ObxaPWmZdv3cgcf55KYB5MTFvfZapR6dgw2uq3tRx75Beowo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
